name: Backend Workflow

on:
  push:
  pull_request:

defaults:
    run:
      working-directory: ./backend

jobs:    
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run lint
    
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run test:unit
      env:
        SALT_ROUNDS: ${{ secrets.SALT_ROUND }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}

  build:
    name: Run build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run build

  deploy:
    name: Deploy to backend branch
    runs-on: ubuntu-latest
    steps:
    - name: Push to branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: deploy/backend
        FOLDER: backend
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


